repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2c8dce6094fa2b4b668e74f694ca63ceffd38614 # pragma: allowlist secret # v0.9.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # pragma: allowlist secret # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/Yelp/detect-secrets
    rev: 01886c8a910c64595c47f186ca1ffc0b77fa5458 # pragma: allowlist secret # v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
